version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
     - dependency-name: "react"
       versions:
         - ">=19.0.0"
     - dependency-name: "react-dom"
       versions:
         - ">=19.0.0"
     - dependency-name: "@types/react"
       versions:
         - ">=19.0.0"
    groups:
      frontend:
        patterns:
          - "*"